### ISSUE TITLE
Webpage only available with www prefix

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/jazz-community.github.io#3]
If I request `http://jazz-community.org/`, a DNS error is shown. The page is only accessible when I request the `www `subdomain. The DNS zone entries need a change to support this. Or even better, we should serve the page on the root domain instead on `www`.

**Comment by schneigu** [comment]
I can add this but it looks like it only works with an A-Record. but not a CNAME. At least at greenIT.

An A-record requires a IP address. e.g. 151.101.112.133 for github.map.fastly.net (address behind jazz-community.github.io)

I did this for the moment.

Btw.
Unfortunately, the DNS specification does not allow CNAME records on the zone itself (the base domain). (For example, MX records would break as the CNAME would be followed to its target first.)

**Comment by schneigu** [comment]
Changed to the published addresses according GIThiub Docu:

https://help.github.com/articles/setting-up-an-apex-domain/#configuring-an-alias-or-aname-record-with-your-dns-provider

Created two A-records with:
192.30.252.153
192.30.252.154

Changed the definition in the project to work without www.
